name: Continuous Integration
on:
  push:
    branch: [master]

jobs:
  unit_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Set Up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.0
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Tests
        env:
          FLASK_ENV: testing
        run: |
          python -m unittest discover src/tests -v
  code_checking:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Set Up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.0
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Checks
        run: |
          flake8 --ignore=E501 src
  # deployment:
  #   needs: 
  #     - unit_testing
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Fresh Repo Clone & Install
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: 
  #         username: 
  #         key: ${{ secrets.SSH_KEY }}
  #         port: 22
  #         script: |
  #           rm -rf ccc_t3a3
  #           git clone https://github.com/AndrewGregorovic/ccc_t3a3.git
  #           python3.8 -m venv /home/<username>/ccc_t3a3/venv
  #           /home/<username>/ccc_t3a3/venv/bin/pip3.8 install -r /home/<username>/ccc_t3a3/requirements.txt
